### ISSUE TITLE
rbe filter seems not be working

### ISSUE THREAD

**Issue by egs2003** [Supergiovane/node-red-contrib-knx-ultimate#21]
The RBE filter does not work. If I repeatedly send the bool true to the node, it will always be output to the BUS.
I have configured a static group address with DPT1

**Comment by Supergiovane** [comment]
Hello,
yes, you're right.
A fix will be out shortly.
Thank you for the feedback!
Don't forget to subscribe, if you wish, to my channel, for news about my nodes.
http://eepurl.com/gJm095

**Comment by Supergiovane** [comment]
Fixed in 1.1.14
Out in minutes.

**Comment by egs2003** [comment]
The error is still present

**Comment by Supergiovane** [comment]
Hello,
the issue has been fixed and tested on 1.1.14. Are you sure? Can you paste here your nodes so i can try directly? Thanks.

**Comment by egs2003** [comment]
[{"id":"7d1a870f.532b08","type":"knxUltimate","z":"3fd3b2c6.bef68e","server":"e4d5887b.163c28","topic":"1/1/1","dpt":"1.001","initialread":true,"notifyreadrequest":false,"notifyresponse":false,"notifywrite":true,"notifyreadrequestalsorespondtobus":false,"notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized":"0","listenallga":false,"name":"","outputtype":"write","outputRBE":false,"inputRBE":false,"x":950,"y":2140,"wires":[[]]},{"id":"7fd9b91c.0f2318","type":"inject","z":"3fd3b2c6.bef68e","name":"","topic":"","payload":"true","payloadType":"bool","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":750,"y":2240,"wires":[["7d1a870f.532b08"]]},{"id":"e4d5887b.163c28","type":"knxUltimate-config","z":"","host":"192.168.178.100","port":"3671","physAddr":"1.1.3","suppressACKRequest":false,"csv":"","KNXEthInterface":"Auto","KNXEthInterfaceManuallyInput":"","statusDisplayLastUpdate":true,"statusDisplayDeviceNameWhenALL":true,"statusDisplayDataPoint":false}]

**Comment by Supergiovane** [comment]
Please check the config. You selected the wrong checkbox.
![Node-RED](https://user-images.githubusercontent.com/37666636/68787159-4ea07180-0641-11ea-9895-01840d84814a.png)

**Comment by egs2003** [comment]
Sorry, I sent you the wrong code. This checkbox was active and it still doesn't work.

**Comment by egs2003** [comment]
I'm checking the bus with ETS. Whenever I trigger the node by inject true is output on the BUS

**Comment by Supergiovane** [comment]
Please see here. You selected a false checkbox.

![Node-RED](https://user-images.githubusercontent.com/37666636/68787502-f322b380-0641-11ea-8070-6ff55e5dbb03.png)

**Comment by egs2003** [comment]
I get it. I wrote that I accidentally sent you the wrong code. But it doesn't work even if the checkbox is activated.

**Comment by Supergiovane** [comment]
Here your code. It works for me.
On the 1/1/1, do you have a real KNX device  or not?

![Node-RED](https://user-images.githubusercontent.com/37666636/68787666-3e3cc680-0642-11ea-922f-dbd4c3f5c382.png)

**Comment by egs2003** [comment]
I have a real KNX system

**Comment by Supergiovane** [comment]
What do you read on the status, below the node?

**Comment by egs2003** [comment]
![Unbenannt](https://user-images.githubusercontent.com/8488313/68787904-a7bcd500-0642-11ea-9e1b-74a4e54b7a03.png)

**Comment by egs2003** [comment]
yes, of course I did a restart, too.

**Comment by Supergiovane** [comment]
Hmm.... What appens if you change the group address?

**Comment by egs2003** [comment]
The problem can be reproduced with other group addresses.

**Comment by Supergiovane** [comment]
Do you have more than one Ethernet interface on your PC?

**Comment by egs2003** [comment]
WLAN and Ethernet

**Comment by Supergiovane** [comment]
Try to disable the Wifi.

**Comment by egs2003** [comment]
Oh, I know what you mean. NodeRed runs on a Raspberry Pi. It is only connected with Ethernet.

**Comment by Supergiovane** [comment]
Or at least, select the ethernet interface in the config node.

![Node-RED](https://user-images.githubusercontent.com/37666636/68788226-46e1cc80-0643-11ea-9130-0a649a885a59.png)

**Comment by Supergiovane** [comment]
Try to manually select the interface in the config node and try again.

**Comment by egs2003** [comment]
Ok I tested it. But it stays with the PRoblem

**Comment by Supergiovane** [comment]
Try to give a name to the node

![Node-RED](https://user-images.githubusercontent.com/37666636/68788409-9d4f0b00-0643-11ea-8835-04645a346faf.png)

**Comment by egs2003** [comment]
That didn't work either

**Comment by Supergiovane** [comment]
What's the make/model of your ETH/KNX interface? Is this a router or an ip interface?

**Comment by egs2003** [comment]
ip interface

**Comment by Supergiovane** [comment]
What version of node-red do you have? 
Are you able to tell me the node.js version as well? In a terminal window, please type 
node -v
Thanks.

**Comment by egs2003** [comment]
node.js v10.17.0
node-red v1.0.2

**Comment by egs2003** [comment]
node-red-contrib-knx-ultimate
1.1.14

**Comment by Supergiovane** [comment]
It seems to be fine.
Maybe some problem while updating the knx-ultimate to 1.1.14?
I need to view what you have in .node-red/node_modules/node-red-contrib-knx-ultimate/knxUltimate-config.js
Are you able to upload here this file?

**Comment by egs2003** [comment]
const knx = require('knx')
const dptlib = require('knx/src/dptlib')
const oOS = require('os')

//Helpers
sortBy = (field) => (a, b) => {
    if (a[field] > b[field]) { return 1 } else { return -1 }
}


onlyDptKeys = (kv) => {
    return kv[0].startsWith("DPT")
}

extractBaseNo = (kv) => {
    return {
        subtypes: kv[1].subtypes,
        base: parseInt(kv[1].id.replace("DPT", ""))
    }
}

convertSubtype = (baseType) => (kv) => {
    let value = `${baseType.base}.${kv[0]}`
    return {
        value: value
        , text: value + ` (${kv[1].name})`
    }
}


toConcattedSubtypes = (acc, baseType) => {
    let subtypes =
        Object.entries(baseType.subtypes)
            .sort(sortBy(0))
            .map(convertSubtype(baseType))

    return acc.concat(subtypes)
}



module.exports = (RED) => {


    RED.httpAdmin.get("/knxUltimateDpts", RED.auth.needsPermission('knxUltimate-config.read'), function (req, res) {
        const dpts =
            Object.entries(dptlib)
                .filter(onlyDptKeys)
                .map(extractBaseNo)
                .sort(sortBy("base"))
                .reduce(toConcattedSubtypes, [])

        res.json(dpts)
    })

    function knxUltimateConfigNode(config) {
        RED.nodes.createNode(this, config)
        var node = this
        node.host = config.host
        node.port = config.port
        node.physAddr = config.physAddr || "15.15.22"; // the KNX physical address we'd like to use
        node.suppressACKRequest = typeof config.suppressACKRequest ==="undefined" ? false:config.suppressACKRequest; // enable this option to suppress the acknowledge flag with outgoing L_Data.req requests. LoxOne needs this
        node.csv = readCSV(config.csv); // Array from ETS CSV Group Addresses
        node.linkStatus = "disconnected";
        node.nodeClients = [] // Stores the registered clients
        node.KNXEthInterface = typeof config.KNXEthInterface === "undefined" ? "Auto" : config.KNXEthInterface;
        node.KNXEthInterfaceManuallyInput = typeof config.KNXEthInterfaceManuallyInput === "undefined" ? "" : config.KNXEthInterfaceManuallyInput; // If you manually set the interface name, it will be wrote here
        node.statusDisplayLastUpdate = config.statusDisplayLastUpdate || true;
        node.statusDisplayDeviceNameWhenALL = config.statusDisplayDeviceNameWhenALL || false;
        node.statusDisplayDataPoint = config.statusDisplayDataPoint || false;
        
        
        // Endpoint for reading csv from the other nodes
        RED.httpAdmin.get("/knxUltimatecsv", RED.auth.needsPermission('knxUltimate-config.read'), function (req, res) {
            res.json(RED.nodes.getNode(node.id).csv);
        });
        // 14/08/2019 Endpoint for retrieving the ethernet interfaces
        RED.httpAdmin.get("/knxUltimateETHInterfaces", RED.auth.needsPermission('knxUltimate-config.read'), function (req, res) {
            var oiFaces = oOS.networkInterfaces();
            var jListInterfaces = [];
            try {
                Object.keys(oiFaces).forEach(ifname => {
                    // Interface with single IP
                    if (Object.keys(oiFaces[ifname]).length === 1) {
                        if (Object.keys(oiFaces[ifname])[0].internal == false) jListInterfaces.push({ name: ifname, address:Object.keys(oiFaces[ifname])[0].address});
                    } else {
                        var sAddresses = "";
                        oiFaces[ifname].forEach(function (iface) {
                            if (iface.internal == false) sAddresses += "+" + iface.address;
                        });
                        if (sAddresses!=="") jListInterfaces.push({ name: ifname, address:sAddresses});
                    }
                })
            } catch (error) {}
            res.json(jListInterfaces)
        });
        
        
        node.setAllClientsStatus = (_status, _color, _text) => {
            function nextStatus(oClient) {
                oClient.setNodeStatus({ fill: _color, shape: "dot", text: _status + " " + _text ,payload: "", GA: oClient.topic, dpt:"", devicename:""})
            }
            node.nodeClients.map(nextStatus);
        }

        node.Disconnect = () => {
            node.setAllClientsStatus("Waiting", "grey", "")
            // Remove listener
            try {
                node.knxConnection.removeListener("event");    
            } catch (error) {
                
            }
            try {
                node.knxConnection.off("event");
            } catch (error) {
                
            }
            node.linkStatus = "disconnected"; // 29/08/2019 signal disconnection
            try {
                node.knxConnection.Disconnect();
            } catch (error) {
            }
            
            node.knxConnection = null;
        }

        node.addClient = (_Node) => {
            // Check if node already exists
            if (node.nodeClients.filter(x => x.id === _Node.id).length === 0) {
                // Check if the node has a valid topic and dpt
                if (_Node.listenallga==false) {
                    if (typeof _Node.topic == "undefined" || typeof _Node.dpt == "undefined") {
                        _Node.setNodeStatus({ fill: "red", shape: "dot", text: "Empty group address (topic) or datapoint.",payload: "", GA: "", dpt:"", devicename:"" })
                        return;
                    } else {
            
                        // Topic must be in formar x/x/x
                        if (_Node.topic.split("\/").length < 3) {
                            _Node.setNodeStatus({ fill: "red", shape: "dot", text: "Wrong group address (topic: " + _Node.topic + ") format.",payload: "", GA: "", dpt:"", devicename:"" })
                            return;
                        }
                    }
                }
                // Add _Node to the clients array
                node.nodeClients.push(_Node)
            }
            // At first node client connection, this node connects to the bus
            if (node.nodeClients.length === 1) {
                // 14/08/2018 Initialize the connection
                node.initKNXConnection();
            }
            if (_Node.initialread) {
                node.readValue(_Node.topic);
            }
        }

      
        node.removeClient = (_Node) => {
            // Remove the client node from the clients array
            //RED.log.info( "BEFORE Node " + _Node.id + " has been unsubscribed from receiving KNX messages. " + node.nodeClients.length);
            try {
                node.nodeClients = node.nodeClients.filter(x => x.id !== _Node.id)
            } catch (error) {}
            //RED.log.info("AFTER Node " + _Node.id + " has been unsubscribed from receiving KNX messages. " + node.nodeClients.length);

              // If no clien nodes, disconnect from bus.
            if (node.nodeClients.length === 0) {
                node.linkStatus = "disconnected";
                node.Disconnect();
            }
        }
      
        
        node.readInitialValues = () => {
            if (node.linkStatus !== "connected") return; // 29/08/2019 If not connected, exit
            if (node.knxConnection) { 
                var readHistory = [];
                let delay = 0;
                node.nodeClients
                    .filter(oClient => oClient.initialread)
                    .forEach(oClient => {
                        if (oClient.listenallga==true) {
                            delay = delay + 200
                            for (let index = 0; index < node.csv.length; index++) {
                                const element = node.csv[index];
                                if (readHistory.includes(element.ga)) return
                                setTimeout(() => node.readValue(element.ga), delay)
                                readHistory.push(element.ga)
                            }
                        } else {
                            if (readHistory.includes(oClient.topic)) return
                            setTimeout(() => node.readValue(oClient.topic), delay)
                            delay = delay + 200
                            readHistory.push(oClient.topic)
                        }
                        
                    })
            }
        }
       
    
        node.readValue = topic => {
            if (node.linkStatus !== "connected") return; // 29/08/2019 If not connected, exit
            if (node.knxConnection) {
                try {
                    node.knxConnection.read(topic)
                } catch (error) {
                    RED.log.error('knxUltimate: readValue: (' + topic + ') ' + error);
                }
                
            }
        }
        
            
        node.initKNXConnection = () => {
            node.Disconnect();
            node.setAllClientsStatus("Waiting", "grey", "")

            var knxConnectionProperties = {
                ipAddr: node.host,
                ipPort: node.port,
                physAddr: node.physAddr, // the KNX physical address we'd like to use
                suppress_ack_ldatareq: node.suppressACKRequest,
                handlers: {
                    connected: () => {
                        node.linkStatus = "connected";
                        node.setAllClientsStatus("Connected", "green", "Waiting for telegram.")
                        node.readInitialValues() // Perform initial read if applicable
                    },
                    error: function (connstatus) {
                        // NO_ERROR: 0x00, // E_NO_ERROR - The connection was established succesfully
                        // E_HOST_PROTOCOL_TYPE: 0x01,
                        // E_VERSION_NOT_SUPPORTED: 0x02,
                        // E_SEQUENCE_NUMBER: 0x04,
                        // E_CONNSTATE_LOST: 0x15, // typo in eibd/libserver/eibnetserver.cpp:394, forgot 0x prefix ??? "uchar res = 21;"
                        // E_CONNECTION_ID: 0x21, // - The KNXnet/IP server device could not find an active data connection with the given ID
                        // E_CONNECTION_TYPE: 0x22, // - The requested connection type is not supported by the KNXnet/IP server device
                        // E_CONNECTION_OPTION: 0x23, // - The requested connection options is not supported by the KNXnet/IP server device
                        // E_NO_MORE_CONNECTIONS: 0x24, //  - The KNXnet/IP server could not accept the new data connection (Maximum reached)
                        // E_DATA_CONNECTION: 0x26,// - The KNXnet/IP server device detected an erro concerning the Dat connection with the given ID
                        // E_KNX_CONNECTION: 0x27,  // - The KNXnet/IP server device detected an error concerning the KNX Bus with the given ID
                        // E_TUNNELING_LAYER: 0x29,
                        node.linkStatus = "disconnected";
                        if (connstatus == "E_KNX_CONNECTION") {
                            setTimeout(() => node.setAllClientsStatus(connstatus, "red", "Error on KNX BUS. Check KNX red/black connector and cable."), 2000)
                            RED.log.error("knxUltimate: Bind KNX Bus to interface error: " + connstatus);
                        } else {
                            setTimeout(() => node.setAllClientsStatus(connstatus, "red", "Error"), 2000)
                            RED.log.error("knxUltimate: knxConnection error: " + connstatus);
                        }
                        
                    }
                }
            };

            if (node.KNXEthInterface !== "Auto")
            {
                var sIfaceName = "";
                if (node.KNXEthInterface === "Manual") {
                    sIfaceName = node.KNXEthInterfaceManuallyInput;
                    RED.log.info("knxUltimate: Bind KNX Bus to interface : " + sIfaceName + " (Interface's name entered by hand)");
                } else {
                    sIfaceName = node.KNXEthInterface;
                    RED.log.info("knxUltimate: Bind KNX Bus to interface : " + sIfaceName + " (Interface's name selected from dropdown list)");
                }

                knxConnectionProperties.interface = sIfaceName;            
            } else {
                RED.log.info("knxUltimate: Bind KNX Bus to interface (Auto)");
            }

            node.knxConnection = new knx.Connection(knxConnectionProperties);
         
            // Handle BUS events
            node.knxConnection.on("event", function (evt, src, dest, rawValue) {
         // if (dest == "0/0/50") RED.log.error("RX FROM BUS : " + src + " " + dest + " " + evt + rawValue);
                // if (dest == "0/0/50") {
                //     node.nodeClients.filter(input => input.notifywrite == true).forEach(input => {
                //     RED.log.error("ID=" + input.id + " " + input.topic + " dest=" + dest + " notifywrite=" + input.notifywrite + " listenallga="+input.listenallga);
                //     });
                // }
                switch (evt) {
                    case "GroupValue_Write": {
                        node.nodeClients
                            .filter(input => input.notifywrite == true)
                            .forEach(input => {
                                if (input.listenallga == true) {
                                    // Get the GA from CVS
                                    let oGA;
                                    try {
                                        oGA=node.csv.filter(sga => sga.ga == dest)[0];
                                    } catch (error) { }
                                    
                                    // 25/10/2019 TRY TO AUTO DECODE
                                    // --------------------------------
                                    if (typeof oGA === "undefined") {
                                        // 25/10/2019 from v. 1.1.11, try to decode and output a datapoint.
                                        let msg = buildInputMessage(src, dest, evt, rawValue, tryToFigureOutDataPointFromRawValue(rawValue,dest), "")
                                        input.setNodeStatus({ fill: "green", shape: "dot", text: "Try to decode",payload: msg.payload, GA: msg.knx.destination, dpt:"", devicename:"" });
                                        input.send(msg)    
                                      // --------------------------------
                                        
                                    } else {
                                        let msg = buildInputMessage(src, dest, evt, rawValue, oGA.dpt, oGA.devicename)
                                        input.setNodeStatus({ fill: "green", shape: "dot", text: "",payload: msg.payload, GA: msg.knx.destination, dpt:msg.knx.dpt, devicename:msg.devicename });
                                        input.send(msg)
                                    }
                                } else if (input.topic == dest) {
                                    
                                    let msg = buildInputMessage(src, dest, evt, rawValue, input.dpt, input.name ? input.name : "")
                                    // Check RBE INPUT from KNX Bus, to avoid send the payload to the flow, if it's equal to the current payload
                                    if (!checkRBEInputFromKNXBusAllowSend(input, msg.payload)) {
                                        input.setNodeStatus({fill: "grey", shape: "ring", text: "rbe block ("+msg.payload+") from KNX",payload: "", GA: "", dpt:"", devicename:""})
                                        return;
                                    };
                                    input.currentPayload = msg.payload;// Set the current value for the RBE input
                                    input.setNodeStatus({fill: "green", shape: "dot", text: "", payload: msg.payload, GA: input.topic, dpt:input.dpt, devicename:""});
                                    //RED.log.error("RX FROM BUS : " + input.id +" " + src + " " + dest + " " + evt)
                                    input.send(msg)
                                }
                            })
                        break;
                    }
                    case "GroupValue_Response": {
                        
                        node.nodeClients
                            .filter(input => input.notifyresponse==true)
                            .forEach(input => {
                                if (input.listenallga==true) {
                                    // Get the DPT
                                    let oGA;
                                    try {
                                        oGA=node.csv.filter(sga => sga.ga == dest)[0];
                                    } catch (error) { }
                                    
                                    // 25/10/2019 TRY TO AUTO DECODE
                                    // --------------------------------
                                    if (typeof oGA === "undefined") {
                                        let msg = buildInputMessage(src, dest, evt, rawValue, tryToFigureOutDataPointFromRawValue(rawValue,dest), "")
                                        input.setNodeStatus({ fill: "green", shape: "dot", text: "Try to decode",payload: msg.payload, GA: msg.knx.destination, dpt:"", devicename:"" });
                                        input.send(msg)    
                                      // --------------------------------
                                        
                                    } else {
                                        let msg = buildInputMessage(src, dest, evt, rawValue, oGA.dpt, oGA.devicename)
                                        input.setNodeStatus({ fill: "blue", shape: "dot", text: "", payload: msg.payload, GA: msg.knx.destination, dpt: msg.knx.dpt, devicename: msg.devicename });
                                        input.send(msg)
                                    }
                                } else if (input.topic == dest) {
                                    let msg = buildInputMessage(src, dest, evt, rawValue, input.dpt, input.name ? input.name : "")
                                    // Check RBE INPUT from KNX Bus, to avoid send the payload to the flow, if it's equal to the current payload
                                    if (!checkRBEInputFromKNXBusAllowSend(input, msg.payload)) {
                                        input.setNodeStatus({ fill: "grey", shape: "ring", text: "rbe INPUT filter applied on " + msg.payload })
                                        return;
                                    };
                                    input.currentPayload = msg.payload; // Set the current value for the RBE input
                                    input.setNodeStatus({ fill: "blue", shape: "dot", text: "", payload: msg.payload, GA: input.topic, dpt:msg.knx.dpt, devicename:msg.devicename });
                                    input.send(msg)
                                }
                            })
                        break;
                    }
                    case "GroupValue_Read": {
                        
                        node.nodeClients
                            .filter(input => input.notifyreadrequest==true)
                            .forEach(input => {
                                if (input.listenallga==true) {
                                    // Get the DPT
                                    let oGA;
                                    try {
                                        oGA=node.csv.filter(sga => sga.ga == dest)[0];
                                    } catch (error) { }
                                    
                                    // 25/10/2019 TRY TO AUTO DECODE
                                    // --------------------------------
                                    if (typeof oGA === "undefined") {
                                        // 25/10/2019 from v. 1.1.11, try to decode and output a datapoint.
                                        let msg = buildInputMessage(src, dest, evt, null, tryToFigureOutDataPointFromRawValue(rawValue,dest), "")
                                        input.setNodeStatus({ fill: "green", shape: "dot", text: "Try to decode",payload: msg.payload, GA: msg.knx.destination, dpt:"", devicename:"" });
                                        input.send(msg)    
                                      // --------------------------------
   
                                } else {
                                        let msg = buildInputMessage(src, dest, evt, null, oGA.dpt, oGA.devicename)
                                        input.setNodeStatus({ fill: "grey", shape: "dot", text: "Read", payload: msg.payload, GA: msg.knx.destination, dpt: msg.knx.dpt, devicename: msg.devicename });
                                        input.send(msg)
                                    }
                                } else if (input.topic == dest) {
                                    let msg = buildInputMessage(src, dest, evt, null, input.dpt, input.name ? input.name : "")
                                    // 24/09/2019 Autorespond to BUS
                                    if (input.notifyreadrequestalsorespondtobus===true) {
                                        if (typeof input.currentPayload === "undefined" || input.currentPayload === "") {
                                            setTimeout(() => {
                                                node.knxConnection.respond(dest, input.notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized, input.dpt);
                                                input.setNodeStatus({ fill: "blue", shape: "ring", text: "Read & Autorespond with default", payload: input.notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized, GA: input.topic, dpt: msg.knx.dpt, devicename: "" });
                                            }, 200);
                                        } else {
                                            setTimeout(() => {
                                                node.knxConnection.respond(dest, input.currentPayload, input.dpt);    
                                                input.setNodeStatus({ fill: "blue", shape: "ring", text: "Read & Autorespond", payload: input.currentPayload, GA: input.topic, dpt: msg.knx.dpt, devicename: "" });
                                            }, 200);
                                        }
                                    } else {
                                        input.setNodeStatus({ fill: "grey", shape: "dot", text: "Read", payload: msg.payload, GA: input.topic , dpt:msg.knx.dpt, devicename:"" });    
                                    }
                                    input.send(msg)
                                    
                                }
                            })
                        break;
                    }
                    default: return
                }
            })
        }
        

       

  
        // 26/10/2019 Try to figure out the datapoint type from raw value
        function tryToFigureOutDataPointFromRawValue(_rawValue) {
            // 25/10/2019 Try some Datapoints
            if (_rawValue.length == 1) {
                if (_rawValue[0].toString() == "0" || _rawValue[0].toString() == "1") {
                    return "1.001"; // True/False?
                } else {
                    return "5.001"; // Absolute Brightness ?       
                }
            } else if (_rawValue.length == 4) {
                return "14.056"; // Watt ?
            } else if (_rawValue.length == 2) {
                return "9.001"; 
            } else if (_rawValue.length == 14) {
                return "16.001"; // Text ?
            } else {
                // Dont' know, try until no errors
                let dpts =
                    Object.entries(dptlib)
                        .filter(onlyDptKeys)
                        .map(extractBaseNo)
                        .sort(sortBy("base"))
                        .reduce(toConcattedSubtypes, []);
                for (let index = 0; index < dpts.length; index++) {
                    const element = dpts[index];
                    try {
                        //dpt.value)
                        //dpt.text))
                        var dpt = dptlib.resolve(element.value);
                        if (typeof dpt !== "undefined")
                        {
                            var jsValue = dptlib.fromBuffer(_rawValue, dpt)
                            if (typeof jsValue !== "undefined") { 
                                //RED.log.info("Trying for " + dest + ". FOUND " + element.value);
                                return element.value;
                            }
                        }
                    } catch (error) {
                        
                    }                        
                }
            }
        }


        // 14/08/2019 If the node has payload same as the received telegram, return false
        checkRBEInputFromKNXBusAllowSend = (_node, _KNXTelegramPayload) => {
            if (_node.inputRBE !== true) return true;
            if (_node.listenallga) return true;

            if (typeof _node.currentPayload === "undefined") {
                _node.currentPayload = _KNXTelegramPayload;
                return true;
            } 

            var curVal = _node.currentPayload.toString().toLowerCase();
            var newVal = _KNXTelegramPayload.toString().toLowerCase();
            if (curVal==="false") {
                curVal = "0";
            }
            if (curVal==="true") {
                curVal = "1";
            }
            if (newVal==="false") {
                newVal = "0";
            }
            if (newVal==="true") {
                newVal = "1";
            }
            if (curVal === newVal) {
                 return false;
            }

            // Set the current value for the RBE input
            _node.currentPayload = _KNXTelegramPayload;
            return true;
        }
        


        function buildInputMessage(src, dest, evt, value, inputDpt, _devicename) {
            // Resolve DPT and convert value if available
            //if (dest=="0/0/50") RED.log.error("Buildinputmessage src=" + src + " dest" + dest + " value=" + value + " inputDpt=" + inputDpt + " _devicename="+_devicename);
            var dpt = dptlib.resolve(inputDpt)
            var jsValue = null
            if (dpt && value) {
                var jsValue = dptlib.fromBuffer(value, dpt)
            }

            // Build final input message object
            return {
                topic: dest
                , payload: jsValue
                , knx:
                {
                    event: evt
                    , dpt: inputDpt
                    //, dptDetails: dpt
                    , source: src
                    , destination: dest
                    , rawValue: value
                }
                , devicename: (typeof _devicename !== 'undefined') ? _devicename : ""
            }
        }
    

        node.on("close", function () {
            node.Disconnect();
        })
 
        function readCSV(_csvText) {
                
            var ajsonOutput = new Array(); // Array: qui va l'output totale con i nodi per node-red
           
            if (_csvText == "") {
                RED.log.info('knxUltimate: no csv ETS found');
                return;
            } else {
                RED.log.info('knxUltimate: csv ETS found !');
                // 23/08/2019 Delete inwanted CRLF in the GA description
                let sTemp = correctCRLFInCSV(_csvText);
                
                // Read and decode the CSV in an Array containing:  "group address", "DPT", "Device Name"
                let fileGA = sTemp.split("\n");
                // Controllo se le righe dei gruppi contengono il separatore di tabulazione
                if (fileGA[0].search("\t") == -1) {
                    RED.log.error('knxUltimate: ERROR: the csv ETS file must have the tabulation as separator')
                    return;
                }
    
                var sFirstGroupName = "";
                var sSecondGroupName = "";
                var sFather="";
                for (let index = 0; index < fileGA.length; index++) {
                    var element = fileGA[index];
                    element = element.replace(/\"/g, ""); // Rimuovo le virgolette
                
                    if (element !== "") {
                        
                        // Main and secondary group names
                        if ((element.split("\t")[1].match(/-/g) || []).length == 2) {
                            // Found main group family name (Example Light Actuators)
                            sFirstGroupName = element.split("\t")[0] || "";
                            sSecondGroupName = "";
                        }
                        if ((element.split("\t")[1].match(/-/g)||[]).length==1) {
                            // Found second group family name (Example First Floor light)
                            sSecondGroupName = element.split("\t")[0] || "";
                        }
                        if(sFirstGroupName!=="" && sSecondGroupName !==""){sFather="(" + sFirstGroupName + "->" +sSecondGroupName + ") " }
                       
                        if (element.split("\t")[1].search("-") == -1 && element.split("\t")[1].search("/") !== -1) {
                            // Ho trovato una riga contenente un GA valido, cioè con 2 "/"
                            if (element.split("\t")[5] == "") {
                                RED.log.error("knxUltimate: ERROR: Datapoint not set in ETS CSV. Please set the datapoint with ETS and export the group addresses again. ->" + element.split("\t")[0] + " " + element.split("\t")[1])
                                return;
                            }
                            var DPTa = element.split("\t")[5].split("-")[1];
                            var DPTb = element.split("\t")[5].split("-")[2];
                            if (typeof DPTb == "undefined") {
                                RED.log.warn("knxUltimate: WARNING: Datapoint not fully set (there is only the first part on the left of the '.'). I applied a default .001, but please set the datapoint with ETS and export the group addresses again. ->" + element.split("\t")[0] + " " + element.split("\t")[1] + " Datapoint: " + element.split("\t")[5] );
                                DPTb = "001"; // default
                            }
                            // Trailing zeroes
                            if (DPTb.length == 1) {
                                DPTb = "00" + DPTb;
                            } else if (DPTb.length == 2) {
                                DPTb = "0" + DPTb;
                            } if (DPTb.length == 3) {
                                DPTb = "" + DPTb; // stupid, but for readability
                            }
                            ajsonOutput.push({ga:element.split("\t")[1], dpt:DPTa + "." + DPTb, devicename: sFather + element.split("\t")[0]});
                        }
                    }
                }
                
                return ajsonOutput;
            }
    
        }
    
     
        // 23/08/2019 Delete unwanted CRLF in the GA description
        function correctCRLFInCSV(_csv) {
            
            var sOut = ""; // fixed output text to return
            var sChar = "";
            var bStart = false;
            for (let index = 0; index < _csv.length; index++) {
                sChar = _csv.substr(index, 1);
                if (sChar == "\"")
                {
                    if (!bStart) {
                        bStart = true;                        
                    }else
                    {
                        bStart = false;                        
                    }
                    sOut += sChar;

                } else
                {
                    if (bStart) {
                        // i'm in the phrase, delimited by "". No CRLF should be there
                        if (sChar !== "\n" && sChar !== "\r")
                        {
                            sOut += sChar;        
                        } else
                        {
                            sOut += " "; // Where it was a CRLF, i put a space
                        }
                    } else
                    {
                        sOut += sChar; 
                    }
                    
                }
            }

            // Replace all parenthesis with []
            sOut = sOut.replace(/\(/g, "[").replace(/\)/g, "]");
            return sOut;
        }

    }

   

    RED.nodes.registerType("knxUltimate-config", knxUltimateConfigNode);
}

**Comment by egs2003** [comment]
There were no questionable messages during update

**Comment by Supergiovane** [comment]
Ok, let me some time to work this out. I revert to you.

**Comment by Supergiovane** [comment]
The code is OK. There should be another issue. I need you again to paste here the nodes, so i have your exact configuration. Then i'll test with an IP interface (i have an ip router here)

**Comment by Supergiovane** [comment]
Hello again. Are you able to paste this file into .node-red/node_modules/node-red-contrib-knx-ultimate/ folder and restart nodered?
Then try again.

[knxUltimate-config.js.zip](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/files/3842672/knxUltimate-config.js.zip)

**Comment by egs2003** [comment]
nothing has changed

**Comment by Supergiovane** [comment]
Holy crap.

**Comment by egs2003** [comment]
I'm sorry. So I'd get along alternatively, too. But of course it would still be cool if it worked.

**Comment by Supergiovane** [comment]
Have had no messages from users about this issue. I need to try with an ip interface, but i can try it only tomorrow.
Can you do something like this, and try to send a payload to the first node? I need to know what the debug message says. Thanks.

<img width="471" alt="Node-RED" src="https://user-images.githubusercontent.com/37666636/68790798-4a2b8700-0648-11ea-8c31-ba49d296555c.png">

**Comment by egs2003** [comment]
I'm not getting any debug news. Even not if I alternate true and fals send. But in ETS the messages are displayed

**Comment by Supergiovane** [comment]
That's clear. The node value is updated as soon it receives the value from the KNX bus. In you case, the RBE is not the problem. The problem is that the node doesn't receive anything from the bus.

**Comment by Supergiovane** [comment]
Do you have maybe a DDOS protection or UDP flood protection set on any switch or router in your net?

**Comment by egs2003** [comment]
I'm not familiar with that. I deliberately did not set it up or see it anywhere.

**Comment by Supergiovane** [comment]
How many IP tunnels can instantiate your IP interface? You use currently two, one for ETS and one for the knx-ultimate. It can be an issue with the max tunnel number allowed by your interface.

**Comment by Supergiovane** [comment]
What appens to the debug msg node, if you send a value from the ETS itself?

**Comment by egs2003** [comment]
{"topic":"0/1/2","payload":false,"knx":{"event":"GroupValue_Write","dpt":"1.001","source":"1.1.250","destination":"0/1/2","rawValue":[0]},"devicename":"","_msgid":"e2368303.0d35d"}

**Comment by egs2003** [comment]
I use a fritzbox. My interface can have 4 or 5 tunnels.

**Comment by Supergiovane** [comment]
Fritzbox doesn't do any flood protection. So you're ok.
Try this:

Close ETS.
Reboot your ip interface (what model of ip interface do you have?).
Don't open ETS
Try to send a payload to the node and let me know what the debug node says.

**Comment by egs2003** [comment]
I'm afraid I can't find the time today.
The used interface is from mdt
https://www.mdt.de/download/Archiv/MDT_THB_IP_Interface_02.pdf

**Comment by Supergiovane** [comment]
We'll continue tomorrow! Bye

**Comment by egs2003** [comment]
However, the plant was only completely restarted this morning.

**Comment by egs2003** [comment]
However, the system was only completely restarted this morning.

**Comment by Supergiovane** [comment]
i need to go step by step to find what you problem is. Tomorrow!

**Comment by Supergiovane** [comment]
but... still suspect your double ethernet on the PI.
Tomorrow, try to DISABLE the wifi. Bye.

**Comment by egs2003** [comment]
Disabling WiFi did not help

**Comment by Supergiovane** [comment]
Hmmm. Your problem seems to be beyond what i can do for you.

If the problem persists, you can try to:
1) Connect the MDT direclty to your node-red machine, or at least, node-red machine and MDT on the same switch.
2) You can also watch the config of your MDT, maybe there is something preventing the forwarding of the KNX ip messages again to the ethernet interface, or there's some set of filtering on the device ID (Quelleadress) you set in the knx-ultimate
3) Change your Quelleadresse 1.1.3; try to set it on 15.15.1 for example, out of the scope of other devices, on another Line.
4) You can try using others knx nodes, for example knxjs or knxeasy.

One of the above solutions must for sure work. Please tell me wich of these. Thanks!

**Comment by egs2003** [comment]
Sorry, it's a productive system. I will not make such changes. Unfortunately I can't help you there

**Comment by Supergiovane** [comment]
I wish to help you, because with more than 1.000 knx-ultimate installations working 24h, i cannot find the issue for your problem. This is very frustrating but i'm pretty sure, that the knx-ultimate is working correctly. One of the above solutions  (apart from 4.) will for sure work.

**Comment by egs2003** [comment]
For myself I have found a working solution. I use my own RBE filter in front of your node. I didn't look at your implementation either. I assumed that you were checking the payload on the software side.

**Comment by Supergiovane** [comment]
Yes but this is a workaround. In fact, the node cannot receive any telegram sent by another knx-ultimate node itself. The RBE filter built into knx-ultimate, take cares of the real value of the node. 
At a last chance, you can try to check "**suppress ACK Request**" in the knx-ultimate Gateway config node. This option suppresses the ACK request coming from old KNX/IP interfaces.

**Comment by Supergiovane** [comment]
Do you have restarted node-red after changing the Ethernet Interface or disable the wifi?

**Comment by egs2003** [comment]
yes i did

**Comment by Supergiovane** [comment]
V1.1.15 is out. Try that, but for sure it's an ethernet related issue.
