### ISSUE TITLE
Smart Plug stop working

### ISSUE THREAD

**Issue by evazzoler** [Supergiovane/node-red-contrib-knx-ultimate#306]
Hi, I have a on/off smartplug that the hue app controls without issues.
Knx ultimate controls the on/off, too. After a while it stops working and the node gets an error.
![image](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/9479876/05868f30-0f7a-4637-a04d-a94699a53c1a)
It works again when I restart node red and stops working after a while.
I noticed that the error diaspear when I force night or day and comes back when I try to turn the plug on with KNX until I restart node red.

**Comment by Supergiovane** [comment]
Hi,
I’ll take a look, but I don’t have a smart plug, so I’m blind. 
We need probably a new “smart plug node”.

**Comment by Supergiovane** [comment]
Hi Enrico
Tomorrow i should receive a smart hue plug from Amazon.

**Comment by Supergiovane** [comment]
Hi Enrico,
think it's fixed now. Are you so skilled, to replace a file into your .node-red folder?
If yes, please put the content of this zip, into your .node-red/node_modules/node-red-contrib-hikvision-ultimate/nodes folder.
[Archivio.zip](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/files/13760041/Archivio.zip)

**Comment by Supergiovane** [comment]
PS: the smart switch doesn't have the "brightness" service, so i've handled it in the code.

**Comment by Supergiovane** [comment]
Hi Enrico, 
could you give me a feedback on that?
Thanks and... have a nice Christmas!

**Comment by evazzoler** [comment]
Hi Max, sorry for my delay, I had some problems with my daughter. I late give you my best wishes for these holidays.
I've uploaded the files you sent me, but I had temporary fixed the issue cancelling the day/night GA (night function were disabled but enabling-cancelling-disablig was necessary).
Brightness is still present in the menu. I don't know if it should.
